### ISSUE TITLE
Test framework doesn't fail on syntax errors

### ISSUE THREAD

**Issue by Kalekdan** [crazywolf132/Mani#84] opened 2019-07-10 13:32 UTC
**Describe the bug**
When running tests, a syntax error will stop the test being run but will not cause the test to fail. This is an problem as the genuine issue in the test may be overlooked as tests after it will continue to run.

**To Reproduce**
Test to reproduce the behaviour:
``` JS
load "munit";

let t <- newTester();
t.header("Syntax Error Test Bug");

let x = 1;

t.assertEquals(x, 1.prop, "<- assign operator");

t.results();
```
The above test will throw a syntax error due to the 1.prop but will not fail the test, meaning any tests afterwards will continue to run

**Expected behaviour**
When a test encounters a syntax error, it should fail the same as it would if it had met an assertion failure.

**Desktop (please complete the following information):**
 - OS: WINDOWS
 - Version: 10

**Comment by crazywolf132** [comment] 2019-07-17 04:02
Are you talking about when run in a batch test? or a single?

If you are talking about as a single... it does as intended. The test will not even compile.

**Comment by Kalekdan** [comment] 2019-07-17 07:13
An example of this occurring on our CI [here](https://circleci.com/gh/Kalekdan/Mani/36?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) due to using functions which had not yet made it into the stdlib. The test suite passes despite the files test not succeeding

**Comment by crazywolf132** [comment] 2019-07-18 02:11
After carefully looking, i realised the problem was... as it runs multiple files... it ignores the `hadRuntimeError` flag. 

I have created a simple fix for this. Under each test... it checks the system api, if there was an error or not.

Added in commit: 6993fc5

**Closed by crazywolf132** 2019-07-18 02:11 UTC
Labels: bug
